<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="FirefoxTest"
           tests="1"
           failures="1"
           errors="0"
           skipped="0"
           time="21.207">
  <properties />
            <testcase name="checkEmail" time="21.207" classname="automationFramework.TestCases.EmailTest2">
                <failure type="com.sun.mail.util.MailConnectException"
                  message="Couldn&apos;t connect to host, port: pop.gmail.com, 995; timeout -1"
              >
<![CDATA[com.sun.mail.util.MailConnectException: Couldn't connect to host, port: pop.gmail.com, 995; timeout -1;
  nested exception is:
	java.net.ConnectException: Connection timed out: connect
  com.sun.mail.pop3.POP3Store.protocolConnect(POP3Store.java:211)
  javax.mail.Service.connect(Service.java:345)
  javax.mail.Service.connect(Service.java:226)
  automationFramework.TestCases.EmailTest2.checkEmail(EmailTest2.java:67)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
  org.testng.SuiteRunner.run(SuiteRunner.java:240)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
  org.testng.TestNG.run(TestNG.java:1031)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
Caused by: java.net.ConnectException: Connection timed out: connect
  java.net.DualStackPlainSocketImpl.connect0(Native Method)
  java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
  java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
  java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
  java.net.AbstractPlainSocketImpl.connect(Unknown Source)
  java.net.PlainSocketImpl.connect(Unknown Source)
  java.net.SocksSocketImpl.connect(Unknown Source)
  java.net.Socket.connect(Unknown Source)
  java.net.Socket.connect(Unknown Source)
  com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:331)
  com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:238)
  com.sun.mail.pop3.Protocol.<init>(Protocol.java:112)
  com.sun.mail.pop3.POP3Store.getPort(POP3Store.java:265)
  com.sun.mail.pop3.POP3Store.protocolConnect(POP3Store.java:207)
  javax.mail.Service.connect(Service.java:345)
  javax.mail.Service.connect(Service.java:226)
  automationFramework.TestCases.EmailTest2.checkEmail(EmailTest2.java:67)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
  org.testng.SuiteRunner.run(SuiteRunner.java:240)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
  org.testng.TestNG.run(TestNG.java:1031)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
      </failure>

          </testcase>
  
  
  
</testsuite>
